/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nim;

import java.awt.Graphics;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Alec Terwilliger
 */
public class GraphicalNim extends javax.swing.JFrame {

    /**
     * Creates new form GraphicalNim
     */
    public GraphicalNim() {
        initComponents();
        p1t1Button.setEnabled(false);
        p1t2Button.setEnabled(false);
        p1t3Button.setEnabled(false);
        p2t1Button.setEnabled(false);
        p2t2Button.setEnabled(false);
        p2t3Button.setEnabled(false);
    }

    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        gameNim.displayPile(g, this.getWidth()/3, this.getHeight()/6);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        player1Label = new javax.swing.JLabel();
        player2label = new javax.swing.JLabel();
        marblesRemainingLabel = new javax.swing.JLabel();
        p1t1Button = new javax.swing.JButton();
        p1t2Button = new javax.swing.JButton();
        p1t3Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        p2t1Button = new javax.swing.JButton();
        p2t2Button = new javax.swing.JButton();
        p2t3Button = new javax.swing.JButton();
        newGameButton = new javax.swing.JButton();
        remainingText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        player1Label.setText("Player 1");

        player2label.setText("Player 2");

        marblesRemainingLabel.setText("21");

        p1t1Button.setText("Take 1");
        p1t1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1t1ButtonActionPerformed(evt);
            }
        });

        p1t2Button.setText("Take 2");
        p1t2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1t2ButtonActionPerformed(evt);
            }
        });

        p1t3Button.setText("Take 3");
        p1t3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1t3ButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        p2t1Button.setText("Take 1");
        p2t1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2t1ButtonActionPerformed(evt);
            }
        });

        p2t2Button.setText("Take 2");
        p2t2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2t2ButtonActionPerformed(evt);
            }
        });

        p2t3Button.setText("Take 3");
        p2t3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p2t3ButtonActionPerformed(evt);
            }
        });

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        remainingText.setText("marbles remaining");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(player1Label)
                        .addGap(49, 49, 49)
                        .addComponent(marblesRemainingLabel)
                        .addGap(18, 18, 18)
                        .addComponent(remainingText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player2label)
                        .addGap(52, 52, 52))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(p1t1Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p2t1Button)
                        .addGap(37, 37, 37))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1t2Button)
                            .addComponent(p1t3Button))
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(p2t3Button)
                                .addGap(37, 37, 37))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(p2t2Button)
                                .addContainerGap(37, Short.MAX_VALUE))))))
            .addComponent(jScrollPane1)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(newGameButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(player1Label)
                            .addComponent(player2label)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(marblesRemainingLabel)
                            .addComponent(remainingText))))
                .addGap(30, 30, 30)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1t1Button)
                    .addComponent(p2t1Button))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1t2Button)
                    .addComponent(p2t2Button))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1t3Button)
                    .addComponent(p2t3Button))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(newGameButton)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Pile pile1 = new Pile(21);
    Player player1 = new Player("Player 1");
    Player player2 = new Player("Player 2"); 
    Game gameNim = new Game(player1, player2, 21);
    
    private void p1t1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1t1ButtonActionPerformed
        gameNim.removeFromPile(1);
        textArea.setText(textArea.getText() + "\n" + player1.getName() + " took 1 marble \nThere are " + gameNim.getMarblesRemaining() + " marbles remaining. \nIt is " +
                player2.getName() + "'s turn \n");
        marblesRemainingLabel.setText(gameNim.getMarblesRemaining() + "");
        if(gameNim.getMarblesRemaining() < 1)
        {
            p2t1Button.setEnabled(false);
            p2t2Button.setEnabled(false);
            p2t3Button.setEnabled(false);
            textArea.setText(textArea.getText() + "\n" + player1.getName() + " is the winner!");
        }
        else
        {
           p2t1Button.setEnabled(true); 
        }
        
        if (gameNim.getMarblesRemaining() < 2) 
        {
            p2t2Button.setEnabled(false);
        }
        else
        {
        p2t2Button.setEnabled(true);
        }
        if(gameNim.getMarblesRemaining() < 3){
            p2t3Button.setEnabled(false);
        }
        else
        {
            p2t3Button.setEnabled(true);
        }
        
        p1t1Button.setEnabled(false);
        p1t2Button.setEnabled(false);
        p1t3Button.setEnabled(false);
        
        repaint();
    }//GEN-LAST:event_p1t1ButtonActionPerformed

    private void p1t2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1t2ButtonActionPerformed
        gameNim.removeFromPile(2);
        textArea.setText(textArea.getText() + "\n" + player1.getName() + " took 2 marbles \nThere are " + gameNim.getMarblesRemaining() + " marbles remaining. \nIt is " +
                player2.getName() + "'s turn \n");
        marblesRemainingLabel.setText(gameNim.getMarblesRemaining() + "");
        if(gameNim.getMarblesRemaining() < 1)
        {
            p2t1Button.setEnabled(false);
            p2t2Button.setEnabled(false);
            p2t3Button.setEnabled(false);
            textArea.setText(textArea.getText() + "\n" + player1.getName() + " is the winner!");
        }
        else
        {
           p2t1Button.setEnabled(true); 
        }
        
        if (gameNim.getMarblesRemaining() < 2) 
        {
            p2t2Button.setEnabled(false);
        }
        else
        {
        p2t2Button.setEnabled(true);
        }
        if(gameNim.getMarblesRemaining() < 3){
            p2t3Button.setEnabled(false);
        }
        else
        {
            p2t3Button.setEnabled(true);
        }
        p1t1Button.setEnabled(false);
        p1t2Button.setEnabled(false);
        p1t3Button.setEnabled(false);
        
        repaint();
    }//GEN-LAST:event_p1t2ButtonActionPerformed

    private void p1t3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1t3ButtonActionPerformed
        gameNim.removeFromPile(3);
        textArea.setText(textArea.getText() + "\n" + player1.getName() + " took 3 marbles \nThere are " + gameNim.getMarblesRemaining() + " marbles remaining. \nIt is " +
                player2.getName() + "'s turn \n");
        marblesRemainingLabel.setText(gameNim.getMarblesRemaining() + "");
        if(gameNim.getMarblesRemaining() < 1)
        {
            p2t1Button.setEnabled(false);
            p2t2Button.setEnabled(false);
            p2t3Button.setEnabled(false);
            textArea.setText(textArea.getText() + "\n" + player1.getName() + " is the winner!");
        }
        else
        {
           p2t1Button.setEnabled(true); 
        }
        
        if (gameNim.getMarblesRemaining() < 2) 
        {
            p2t2Button.setEnabled(false);
        }
        else
        {
        p2t2Button.setEnabled(true);
        }
        if(gameNim.getMarblesRemaining() < 3){
            p2t3Button.setEnabled(false);
        }
        else
        {
            p2t3Button.setEnabled(true);
        }
        p1t1Button.setEnabled(false);
        p1t2Button.setEnabled(false);
        p1t3Button.setEnabled(false);
        
        repaint();
    }//GEN-LAST:event_p1t3ButtonActionPerformed

    private void p2t1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2t1ButtonActionPerformed
        gameNim.removeFromPile(1);
        textArea.setText(textArea.getText() + "\n" + player2.getName() + " took 1 marble \nThere are " + gameNim.getMarblesRemaining() + " marbles remaining. \nIt is " +
                player1.getName() + "'s turn \n");
        marblesRemainingLabel.setText(gameNim.getMarblesRemaining() + "");
        if(gameNim.getMarblesRemaining() < 1)
        {
            p1t1Button.setEnabled(false);
            p1t2Button.setEnabled(false);
            p1t3Button.setEnabled(false);
            textArea.setText(textArea.getText() + "\n" + player2.getName() + " is the winner!");
        }
        else
        {
           p1t1Button.setEnabled(true); 
        }
        
        if (gameNim.getMarblesRemaining() < 2) 
        {
            p1t2Button.setEnabled(false);
        }
        else
        {
        p1t2Button.setEnabled(true);
        }
        if(gameNim.getMarblesRemaining() < 3){
            p1t3Button.setEnabled(false);
        }
        else
        {
            p1t3Button.setEnabled(true);
        }
        p2t1Button.setEnabled(false);
        p2t2Button.setEnabled(false);
        p2t3Button.setEnabled(false);
        
        repaint();
    }//GEN-LAST:event_p2t1ButtonActionPerformed

    private void p2t2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2t2ButtonActionPerformed
        gameNim.removeFromPile(2);
        textArea.setText(textArea.getText() + "\n" + player2.getName() + " took 2 marbles \nThere are " + gameNim.getMarblesRemaining() + " marbles remaining. \nIt is " +
                player1.getName() + "'s turn \n");
        marblesRemainingLabel.setText(gameNim.getMarblesRemaining() + "");
        if(gameNim.getMarblesRemaining() < 1)
        {
            p1t1Button.setEnabled(false);
            p1t2Button.setEnabled(false);
            p1t3Button.setEnabled(false);
            textArea.setText(textArea.getText() + "\n" + player2.getName() + " is the winner!");
        }
        else
        {
           p1t1Button.setEnabled(true); 
        }
        
        if (gameNim.getMarblesRemaining() < 2) 
        {
            p1t2Button.setEnabled(false);
        }
        else
        {
        p1t2Button.setEnabled(true);
        }
        if(gameNim.getMarblesRemaining() < 3){
            p1t3Button.setEnabled(false);
        }
        else
        {
            p1t3Button.setEnabled(true);
        }
        p2t1Button.setEnabled(false);
        p2t2Button.setEnabled(false);
        p2t3Button.setEnabled(false);
        
        repaint();
    }//GEN-LAST:event_p2t2ButtonActionPerformed

    private void p2t3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p2t3ButtonActionPerformed
        gameNim.removeFromPile(3);
        textArea.setText(textArea.getText() + "\n" + player2.getName() + " took 3 marbles \nThere are " + gameNim.getMarblesRemaining() + " marbles remaining. \nIt is " +
                player1.getName() + "'s turn \n");
        marblesRemainingLabel.setText(gameNim.getMarblesRemaining() + "");
        if(gameNim.getMarblesRemaining() < 1)
        {
            p1t1Button.setEnabled(false);
            p1t2Button.setEnabled(false);
            p1t3Button.setEnabled(false);
            textArea.setText(textArea.getText() + "\n" + player2.getName() + " is the winner!");
        }
        else
        {
           p1t1Button.setEnabled(true); 
        }
        
        if (gameNim.getMarblesRemaining() < 2) 
        {
            p1t2Button.setEnabled(false);
        }
        else
        {
        p1t2Button.setEnabled(true);
        }
        if(gameNim.getMarblesRemaining() < 3){
            p1t3Button.setEnabled(false);
        }
        else
        {
            p1t3Button.setEnabled(true);
        }
        p2t1Button.setEnabled(false);
        p2t2Button.setEnabled(false);
        p2t3Button.setEnabled(false);
        
        repaint();
    }//GEN-LAST:event_p2t3ButtonActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        Random rand = new Random();
        String firstPlayer = JOptionPane.showInputDialog(null,"First Player's Name");
        String secondPlayer = JOptionPane.showInputDialog(null,"Second Player's Name");
        
                
        player1 = new Player(firstPlayer);
        player2 = new Player(secondPlayer);
        gameNim = new Game(player1, player2, 21);
        player1Label.setText(firstPlayer);
        player2label.setText(secondPlayer);
        int whoStarts = rand.nextInt(2 - 1 + 1) + 1;
        if (whoStarts == 1) {
            p1t1Button.setEnabled(true);
            p1t2Button.setEnabled(true);
            p1t3Button.setEnabled(true);
            p2t1Button.setEnabled(false);
            p2t2Button.setEnabled(false);
            p2t3Button.setEnabled(false);
            textArea.setText("It is " + firstPlayer + "'s turn. \n");
        }
        else
        {
            p2t1Button.setEnabled(true);
            p2t2Button.setEnabled(true);
            p2t3Button.setEnabled(true);
            p1t1Button.setEnabled(false);
            p1t2Button.setEnabled(false);
            p1t3Button.setEnabled(false);
            textArea.setText("It is " + secondPlayer + "'s turn. \n");
        }
        repaint();
        
    }//GEN-LAST:event_newGameButtonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicalNim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicalNim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicalNim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicalNim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new GraphicalNim().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel marblesRemainingLabel;
    private javax.swing.JButton newGameButton;
    private javax.swing.JButton p1t1Button;
    private javax.swing.JButton p1t2Button;
    private javax.swing.JButton p1t3Button;
    private javax.swing.JButton p2t1Button;
    private javax.swing.JButton p2t2Button;
    private javax.swing.JButton p2t3Button;
    private javax.swing.JLabel player1Label;
    private javax.swing.JLabel player2label;
    private javax.swing.JLabel remainingText;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
